// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHZizq6zKZEXPvld-rgXohdFPHzDammw',
    appId: '1:96140399504:web:70523475831cab01565915',
    messagingSenderId: '96140399504',
    projectId: 'busgo-5271c',
    authDomain: 'busgo-5271c.firebaseapp.com',
    storageBucket: 'busgo-5271c.firebasestorage.app',
    measurementId: 'G-91SNNCS273',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClXhd_sswVxByJ5Xb9wAaFz1k11RIkvlo',
    appId: '1:96140399504:android:f4c05d8b3b050629565915',
    messagingSenderId: '96140399504',
    projectId: 'busgo-5271c',
    storageBucket: 'busgo-5271c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrc-fXhKS4lhOfDEHKubJWEKen-QpbUTw',
    appId: '1:96140399504:ios:f07187ae6bfa6a16565915',
    messagingSenderId: '96140399504',
    projectId: 'busgo-5271c',
    storageBucket: 'busgo-5271c.firebasestorage.app',
    iosClientId: '96140399504-3741m97iul13lfv5mhif7hi9j8m151n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication12',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrc-fXhKS4lhOfDEHKubJWEKen-QpbUTw',
    appId: '1:96140399504:ios:f07187ae6bfa6a16565915',
    messagingSenderId: '96140399504',
    projectId: 'busgo-5271c',
    storageBucket: 'busgo-5271c.firebasestorage.app',
    iosClientId: '96140399504-3741m97iul13lfv5mhif7hi9j8m151n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOHZizq6zKZEXPvld-rgXohdFPHzDammw',
    appId: '1:96140399504:web:bd7ddab71c65fd4c565915',
    messagingSenderId: '96140399504',
    projectId: 'busgo-5271c',
    authDomain: 'busgo-5271c.firebaseapp.com',
    storageBucket: 'busgo-5271c.firebasestorage.app',
    measurementId: 'G-K35GJ6CXB3',
  );
}
